### PR TITLE
Issue #12: Tests for the demand function 

### PR DESCRIPTION
**Pull request by mdesevricourt**
I created 4 tests for the demand function submitted by Julie.

In the process, I spotted a typo in the demand function which I corrected. I also commented the example at the end.

### CODE REVIEW

**Comment by JulieLen** [comment]
Sorry for the typo, yes it was supposed to be "pref". 

I don't see any changes that would  correspond to commenting on the example, are you sure you saved them ?

In some of your tests you use "CourseMatch.demand" to call the function and in others you use "demand" only, is that a typo or did the export function allow you to use only "demand" instead of "CourseMatch.demand" ?


PS : Julia tip : if you want to write on several lines without having to put a # at the beginning of each line you can put #= before you start your paragraph and =# at the end of the paragraph

**Comment by floswald** [comment]
good work on the tests there! finally! :-)

**Comment by mdesevricourt** [comment]
@JulieLen If you look at line 62 to 82 of the demand function file I've added # at the beginning of each to transform the example into a comment (I didn't you could comment several lines at once!).

I think the export statement makes it so that I can only use demand() and I don't have to write Courseparck.demand() but I should have been more coherent. Anyway it worked on my computer.

**Comment by JulieLen** [comment]
Right ! Anyway in my last pull request I documented the functions the way Florian wanted us to and I put the example in the good format 😃

**Pull request closed without merging**
